"""empty message

Revision ID: 55530ee131f2
Revises: 26a4b1456762
Create Date: 2021-01-09 13:31:30.886463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55530ee131f2'
down_revision = '26a4b1456762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currencyType', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
